// <auto-generated/>

namespace ClubMembership.Web.Data
{
  // Warning: This file is generated, do not manually update

  using System;
  using System.Collections.Generic;

  public partial class Member
  {
    public int Id { get; set; }

    // Common fields
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string BirthDate { get; set; }
  }
}
