// <auto-generated/>

namespace ClubMembership.Web.Data
{
  // Warning: This file is generated, do not manually update

  using System;
  using System.Collections.Generic;

  public partial class User
  {
    public int Id { get; set; }

    // Common fields
    public string Email { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }
  }
}
